name: Pre-Commit Checks

on:
  push:
    branches:
      - new_feature
      - main
  pull_request:
    branches:
      - main # Adjust this branch name as needed

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install mypy
          pip install pytest pytest-cov

      - name: Run Pre-Commit Checks
        run: |
          ruff
          mypy .
          pytest --cov=. --cov-report=xml

      - name: Print coverage results
        run: |
          cat coverage
