name: Pre-Commit Checks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Project
        run: poetry install --no-interaction

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install ruff
      #     pip install mypy
      #     pip install pytest pytest-cov

      - name: Run Pre-Commit Checks
        run: |
          source .venv/bin/activate
          ruff check --fix .
          ruff format .
          mypy --explicit-package-bases .
          pytest --cov=. --cov-report=xml

      - name: Print coverage results
        run: |
          cat coverage
